version: 2.1
orbs:
  jira: circleci/jira@1.3.1
jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
  
      - checkout
      - setup_remote_docker
      - run:
          name: build docker images
          command: |
            docker build -t gudditi/monkey:latest .
      - run:
          name: push the image to docker hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push gudditi/monkey:latest

workflows:
  build_and_test:
    jobs:
      - build:
          post-steps:
            - jira/notify