version: 2.1
env:
   IMAGE_TAG=$(date +%Y%m%d-%H%M%S)


jobs:
  build:
    docker:
      - image: gudditi/docker:latest
    steps:
  
      - checkout
      - setup_remote_docker

      - run:
          name: Update ECS task definition and deploy new image
          command: |
            IMAGE_TAG=$(date +%Y%m%d-%H%M%S)
            ECR_REPO=public.ecr.aws/q8s7n8c2/ecr-988
            ECR_IMAGE=$ECR_REPO:$IMAGE_TAG
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO
            docker build -t $ECR_IMAGE .
            docker push $ECR_IMAGE
            aws ecs register-task-definition \
              --family monkey \
              --container-definitions '[{"name":"mycontainer","image":"'$ECR_IMAGE'","cpu":10,"memory":512}]'
            aws deploy create-deployment \
              --application-name myapp \
              --deployment-group-name mydg \
              --revision '{"revisionType":"ECS","ecsRevision":{"taskDefinition":"arn:aws:ecs:REGION:ACCOUNT_ID:task-definition/monkey:REVISION"}}' \
              --deployment-config-name CodeDeployDefault.ECSLinear10PercentEveryMinute

      
workflows:
  build_and_test:
    jobs:
      - build
