version: 2.1
env:
   IMAGE_TAG=$(date +%Y%m%d-%H%M%S)

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
  
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache python3 py3-pip && pip3 install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region $AWS_REGION
      - run:
          name: Build and push Docker image
          command: |
            IMAGE_TAG=$(date +%Y%m%d-%H%M%S)
            docker build -t public.ecr.aws/q8s7n8c2/ecr-988:$IMAGE_TAG .
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q8s7n8c2
            docker push public.ecr.aws/q8s7n8c2/ecr-988:$IMAGE_TAG
      - run:
          name: Update ECS task definition with new image
          command: |
            ECR_IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_ECR_REPOSITORY:$IMAGE_TAG
            TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition $AWS_ECS_TASK_DEFINITION)
            echo $TASK_DEFINITION | jq --arg ECR_IMAGE_URI $ECR_IMAGE_URI '.taskDefinition.containerDefinitions[0].image = $ECR_IMAGE_URI' > task_definition.json
            aws ecs register-task-definition --cli-input-json file://task_definition.json
       
workflows:
  build_and_test:
    jobs:
      - build
