version: 2.1
jobs:
  build:
    docker:
      - image: gudditi/ubuntu:latest
    steps:
      - run:
          name: Start Docker daemon
          command: |
            sudo service docker start
      - checkout
      - run:
          name: build docker images
          command: |
            docker build -t gudditi/monkey:latest .
      - run:
          name: push the image to docker hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push gudditi/monkey:latest

workflows:
  build_and_test:
    jobs:
      - build
