version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.7-git
    steps:
  
      - checkout
      - setup_remote_docker
      - run:
          name: build docker images
          command: |
            docker build -t gudditi/monkey:$(date +%Y%m%d-%H%M%S) .
      - run:
          name: push the image to docker hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push gudditi/monkey:$(date +%Y%m%d-%H%M%S)
workflows:
  build_and_test:
    jobs:
      - build